extends Control

#Stats
@onready var label_name = $MarginContainer_Transparencia/PanelContainer_Fondo/MarginContainer_MargenMenu/PanelContainer_Frente/MarginContainer_Frente/HBoxContainer/MarginContainer_Stats/GridContainer/PlayerName_Container/Label_NAME
@onready var label_lvl = $MarginContainer_Transparencia/PanelContainer_Fondo/MarginContainer_MargenMenu/PanelContainer_Frente/MarginContainer_Frente/HBoxContainer/MarginContainer_Stats/GridContainer/PlayerLevel_Container/Label_LVL
@onready var label_vita_lvl = $MarginContainer_Transparencia/PanelContainer_Fondo/MarginContainer_MargenMenu/PanelContainer_Frente/MarginContainer_Frente/HBoxContainer/MarginContainer_Stats/GridContainer/Vitality_Container/Label_VITA_LVL
@onready var label_sta_lvl = $MarginContainer_Transparencia/PanelContainer_Fondo/MarginContainer_MargenMenu/PanelContainer_Frente/MarginContainer_Frente/HBoxContainer/MarginContainer_Stats/GridContainer/Stamina_Container3/Label_STA_LVL
@onready var label_prec_lvl = $MarginContainer_Transparencia/PanelContainer_Fondo/MarginContainer_MargenMenu/PanelContainer_Frente/MarginContainer_Frente/HBoxContainer/MarginContainer_Stats/GridContainer/Precision_Container2/Label_PREC_LVL
@onready var label_vis_lvl = $MarginContainer_Transparencia/PanelContainer_Fondo/MarginContainer_MargenMenu/PanelContainer_Frente/MarginContainer_Frente/HBoxContainer/MarginContainer_Stats/GridContainer/Vision_Container8/Label_VIS_LVL
@onready var label_sci_lvl = $MarginContainer_Transparencia/PanelContainer_Fondo/MarginContainer_MargenMenu/PanelContainer_Frente/MarginContainer_Frente/HBoxContainer/MarginContainer_Stats/GridContainer/Science_Container6/Label_SCI_LVL
@onready var label_ball_lvl = $MarginContainer_Transparencia/PanelContainer_Fondo/MarginContainer_MargenMenu/PanelContainer_Frente/MarginContainer_Frente/HBoxContainer/MarginContainer_Stats/GridContainer/Ballistics_Container9/Label_BALL_LVL
@onready var label_cyph_lvl = $MarginContainer_Transparencia/PanelContainer_Fondo/MarginContainer_MargenMenu/PanelContainer_Frente/MarginContainer_Frente/HBoxContainer/MarginContainer_Stats/GridContainer/Cypher_Container5/Label_CYPH_LVL
@onready var label_lck_lvl = $MarginContainer_Transparencia/PanelContainer_Fondo/MarginContainer_MargenMenu/PanelContainer_Frente/MarginContainer_Frente/HBoxContainer/MarginContainer_Stats/GridContainer/Luck_Container4/Label_LCK_LVL

#Outcome
@onready var label_max_hp = $MarginContainer_Transparencia/PanelContainer_Fondo/MarginContainer_MargenMenu/PanelContainer_Frente/MarginContainer_Frente/HBoxContainer/MarginContainer_Resultados/GridContainer2/VitalityPoints_MAX/Label_MAX_HP
@onready var label_sta_points_max = $MarginContainer_Transparencia/PanelContainer_Fondo/MarginContainer_MargenMenu/PanelContainer_Frente/MarginContainer_Frente/HBoxContainer/MarginContainer_Resultados/GridContainer2/StaminaPoints_Container3/Label_STA_POINTS_MAX
@onready var label_prec_pctg = $MarginContainer_Transparencia/PanelContainer_Fondo/MarginContainer_MargenMenu/PanelContainer_Frente/MarginContainer_Frente/HBoxContainer/MarginContainer_Resultados/GridContainer2/PrecisionPercentaje_Container2/Label_PREC_PCTG
@onready var label_vis_m = $MarginContainer_Transparencia/PanelContainer_Fondo/MarginContainer_MargenMenu/PanelContainer_Frente/MarginContainer_Frente/HBoxContainer/MarginContainer_Resultados/GridContainer2/VisionDistance_Container8/Label_VIS_M
@onready var label_str_throw_dist = $MarginContainer_Transparencia/PanelContainer_Fondo/MarginContainer_MargenMenu/PanelContainer_Frente/MarginContainer_Frente/HBoxContainer/MarginContainer_Resultados/GridContainer2/ThrowDist_Container7/Label_STR_THROW_DIST
@onready var label_weight_max = $MarginContainer_Transparencia/PanelContainer_Fondo/MarginContainer_MargenMenu/PanelContainer_Frente/MarginContainer_Frente/HBoxContainer/MarginContainer_Resultados/GridContainer2/Strength_Container8/Label_WEIGHT_MAX
@onready var label_exp_dmg_mult = $MarginContainer_Transparencia/PanelContainer_Fondo/MarginContainer_MargenMenu/PanelContainer_Frente/MarginContainer_Frente/HBoxContainer/MarginContainer_Resultados/GridContainer2/Strength_Container9/Label_EXP_DMG_MULT
@onready var label_laser_dmg_mult = $MarginContainer_Transparencia/PanelContainer_Fondo/MarginContainer_MargenMenu/PanelContainer_Frente/MarginContainer_Frente/HBoxContainer/MarginContainer_Resultados/GridContainer2/Science_Container6/Label_LASER_DMG_MULT
@onready var label_ball_dmg_mult = $MarginContainer_Transparencia/PanelContainer_Fondo/MarginContainer_MargenMenu/PanelContainer_Frente/MarginContainer_Frente/HBoxContainer/MarginContainer_Resultados/GridContainer2/Ballistics_Container9/Label_BALL_DMG_MULT
@onready var label_cyph_dmg_mult = $MarginContainer_Transparencia/PanelContainer_Fondo/MarginContainer_MargenMenu/PanelContainer_Frente/MarginContainer_Frente/HBoxContainer/MarginContainer_Resultados/GridContainer2/Cypher_Container5/Label_CYPH_DMG_MULT
@onready var label_lck_chance = $MarginContainer_Transparencia/PanelContainer_Fondo/MarginContainer_MargenMenu/PanelContainer_Frente/MarginContainer_Frente/HBoxContainer/MarginContainer_Resultados/GridContainer2/Luck_Container4/Label_LCK_CHANCE



# Called when the node enters the scene tree for the first time.
func _ready():
	pass # Replace with function body.


# Called every frame. 'delta' is the elapsed time since the previous frame.
func _process(delta):
	pass
